### ISSUE TITLE
Could you provide a simpy instruction to run the code？

### ISSUE THREAD

**Issue by zzy-2021** [chengine/catnips#1]
Thank you for your great work!

When I attempt to run the code on my machine, I cannot run it  smoothly. Specifically, there are some questions:

1) There are four python file under the **catnips fold**, including **'run.py'**, **'run_catnips.py'**, **'run_catnips_ros.py'** and **'run_nerf_nav.py'**.  Which one is the **entrance** to run the catnips?

2) **Before** runing the catnips, do we need to create NeRFs and PURR representations? It seems that there is **no** relevant part of the code.

3) I'm very interesting in your work, can you provide the pre-trained models or the **instruction** to run the total pipeline?

Thank!

**Comment by chengine** [comment]
The Readme has been updated. Let me know if you still have questions!
